<a href="https://colab.research.google.com/github/CiberNefty/Numpy_Pandas_CienciaDatos_V01/blob/main/Platz/Numpy/02_Indexacion_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
array = np.array([10,20,30,40,50])
print(array[1])
print(array[4])
print(array[-1])

20
50
50


In [ ]:
# Acceder a susbconjuntos
print(array[1:3]) # Traer ciertos datos

[20 30]


In [ ]:
print(array[1:7])

[20 30 40 50]


In [ ]:
print(array[-1:-7])

[]


In [ ]:
# Indexacion Booleana
# Hacer una consulta que que valores estan dentro de cierta coindicion
array = np.array([10,20,30,40,50])
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [ ]:
# Acceder a multiples coleeciones del arra, desde una especificacion de una lista ya establecida
index = [2,0,4] # Posiciones
print(array[index])


[30 10 50]


In [7]:
# Acceder a multiples posiciones de varias dimensiones
array = np.random.randint(1,11, size = (3,3))
print(array)
print(array[2,0])

[[5 6 4]
 [3 2 8]
 [1 5 8]]
1


In [ ]:
# Extraccion de cortes de mayor longitud de una matriz de varias notaciones
print(array[:3,:2]) # SubArray

[[6 6 1]
 [6 5 3]
 [7 9 2]]


# **EJERCICIOS**

In [ ]:
# Crea un arreglo de 10 numeros y accede al cuarto y penúltimo elemento usando indices positivos y negativos
arreglo1 = np.array([1,2,3,4,5,6,7,8,9,10])
indices_posi = [3,8]
indices_nega = [-7,-2]
print(arreglo1[indices_posi])
print(arreglo1[indices_nega])

[4 9]
[4 9]


In [40]:
# 2. Slicing de arrreglo:
# * Dado un arreglo de numero del 1 al 20, extrae los elementos entre las posiciones 3 y 7 , y luego los elementos de las ultimas 5 posiciones.
arreglo2 = np.arange(1,21)
indices2 = [3,8]
print(arreglo2[indices2])
print(arreglo2[15:21]) # Slicing
print(arreglo2[-5:]) # Slicing

[4 9]
[16 17 18 19 20]
[16 17 18 19 20]


In [ ]:
# 3. Indexing con booleanos:
#  Crea un arreglo de numeros aleatorios entre 0 y 100, Usa una expresion booleana para acceder solo a los numeros mayores a 50
arreglo3 = np.random.randint(0,101, size=100)
mascara = (arreglo3 >50) #& (arreglo3 <101)
#print(arreglo3)
print(arreglo3[mascara])

[ 86  22   9  25  22  25  58   5  75  69  78  55  56  36  94  73  74   2
  37  91  31  80  58  45  72  63  11 100  18  26  53  61  24  26  17  65
  82  34  69  21  22   5  78  39  42  78  76  82  85  40  85  54  98  16
  62  61  28   3  10  55  25  11   3  91  95  47  23  69  25  82  43  96
  23  92  49  32  17   0  17  33  66  35  90  37  24  34  24  27  99  45
  90  65   3  87  89  68  84  71  61   8]
[ 86  58  75  69  78  55  56  94  73  74  91  80  58  72  63 100  53  61
  65  82  69  78  78  76  82  85  85  54  98  62  61  55  91  95  69  82
  96  92  66  90  99  90  65  87  89  68  84  71  61]


In [ ]:
# 4. Indexacion con multiples indices
# * Dado un arreglo de 8 elementos, crea una lista de indices para acceder a los elementos en las posiciones 1,4 y 6.
arreglo4 = np.array([10,2,23,84,5,56,67,18])
lista_indices1 = [[1],[4],[6]] # Esto es una lista de listas
lista_indices2 = [1,4,6]
print(f"Respuesta: {arreglo4[lista_indices2]}")
print(f"Lista indices 1 (matrix 3x1): {arreglo4[lista_indices1].shape}")
print(f"Lista indices 2: {arreglo4[lista_indices2].shape}")
print(len(arreglo4))

Respuesta: [ 2  5 67]
Lista indices 1 (matrix 3x1): (3, 1)
Lista indices 2: (3,)
8


In [56]:
# 5. Matrices bidemensionales:
# * Genera una matriz de 4x4 de numero aleatorios entre 10 y 50, y accede a la submatriz de 2x2 ubucada en la esquina inferioir derecha

matrix1 = np.array([
 [1,2,3,4],
 [5,6,7,8],
 [9,10,11,12],
 [13,14,15,16]]) # 4X4
matrix1

dimension1 = np.random.randint(10,51, size=(4,4))
print(dimension1)
print(dimension1[2,2])
print(dimension1[2:, 2:]) # Slicing


[[34 43 18 11]
 [10 49 15 42]
 [26 47 25 46]
 [17 32 10 48]]
25
[[25 46]
 [10 48]]


In [83]:
# 6. Crea un arreglo de dimensiones (2, 3, 4) con números del 1 al 24.
# Objetivos:
#
# Mostrar la forma (shape) del arreglo.
# Mostrar el número de dimensiones (ndim).
# Acceder al elemento ubicado en:
#   *Primer bloque
#   *Segunda fila
#   *Tercera columna
# Extraer la segunda matriz completa (bloque índice 1).

arreglo_dinemsional = np.array(
[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
 [[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print(f"Arreglo dimensonal completo: \n{arreglo_dinemsional}")
print(f"Forma del arreglo (shape):{arreglo_dinemsional.shape}")
print(f"Numero de dimensiones (ndim): {arreglo_dinemsional.ndim}")
print(f"Elemento ubicado en (0,1,2): {arreglo_dinemsional[0,1,2]}")
print(f"Segunda Matriz completa: {arreglo_dinemsional[1]}")


Arreglo dimensonal completo: 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Forma del arreglo (shape):(2, 3, 4)
Numero de dimensiones (ndim): 3
Elemento ubicado en (0,1,2): 7
Elemento ubicado en (0,1,2): [ 1 13]
Segunda Matriz completa: [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [93]:
# 7. Submatrices y dimesniones:
# Genera una matriz aleatoria de tamaño (5, 5) con números entre 1 y 100.
#Objetivos:
# Mostrar la matriz completa.
# Mostrar su forma (shape).
# Extraer:
#   * La primera fila.
#   * La última columna.
#   * La submatriz central de tamaño 3x3.
# Mostrar la dimensión de la submatriz obtenida.

matriz_aleatoria = np.random.randint(1,101, size=(5,5))
print(f"Matriz completa aleatoria (5x5):\n{matriz_aleatoria}")

print(f"Forma Shape: {matriz_aleatoria.shape}")
print(f"Estraxcion primera fila: {matriz_aleatoria[0]}")
print(f"Estraxcion ultima columna: {matriz_aleatoria[:,4]}")
print(f"Estraxcion la submatriz central de tamaño 3x3: {matriz_aleatoria[1:1:3, 3:2:3]}")
submatriz_aleatoria = matriz_aleatoria[1:4, 1:4]
print(f"Estraxcion la submatriz central de tamaño 3x3:\n{submatriz_aleatoria}")


Matriz completa aleatoria (5x5):
[[ 51   4  94  74  52]
 [ 36  16  79  55  87]
 [  7  81  74  55  66]
 [ 48  49  37  43  26]
 [ 11  12  44  43 100]]
Forma Shape: (5, 5)
Estraxcion primera fila: [51  4 94 74 52]
Estraxcion ultima columna: [ 52  87  66  26 100]
Estraxcion la submatriz central de tamaño 3x3: []
Estraxcion la submatriz central de tamaño 3x3:
[[16 79 55]
 [81 74 55]
 [49 37 43]]
