<a href="https://colab.research.google.com/github/CiberNefty/Numpy_Pandas_CienciaDatos_V01/blob/main/Platz/Numpy/03_Operaciones_con_Arrasy_Broadcastin_concatenacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Broadcasting**

```
Es cuando NumPy expande arrays automáticamente para poder operar aunque no tengan la misma forma.
```



In [1]:
import numpy as np

In [4]:
prices = np.array([100,200,300])
discount = np.array([0.9])
discount_price = prices*discount
print(discount_price)

[ 90. 180. 270.]


In [7]:
prices = np.random.randint(100,500, size=(3,3))
discount = np.array([10,20,30])
discount_price = prices+discount
print(prices)
print(discount_price)

[[305 285 464]
 [411 418 440]
 [416 282 171]]
[[315 305 494]
 [421 438 470]
 [426 302 201]]


**Operaciones logicas**

In [9]:
array = np.array([1,2,3,4,5])
print(np.all(array > 91))
print(np.any(array > 2))

False
True


**Concatenacion**

In [17]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated_a = np.concatenate((array_a, array_a))
concatenated_ab = np.concatenate((array_a, array_b))
print(concatenated_a)
print(concatenated_ab)

[1 2 3 1 2 3]
[1 2 3 4 5 6]


**Staking**:

Una forma de apilar arrays

In [20]:
satecked_v = np.vstack((array_a,array_b))
print(f"vertical:\n{satecked_v}")
satecked_h = np.hstack((array_a,array_b))
print(f"Horizontal: {satecked_h}")

vertical: [[1 2 3]
 [4 5 6]]
Horizontal: [1 2 3 4 5 6]


**Split**

In [31]:
array_c = np.arange(1,10)
split_array = np.split(array_c,3)
print(split_array)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


**Ejercicios:**

In [35]:
# 1. Broadcasting

a = np.array([[1],[2],[3]])
b = np.array([10,20,30])
print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [41]:
# 2. Concatenacion
# Une arrays en un eje específico.
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
concatenated = np.concatenate((a, b), axis=0)
print(concatenated)


[[1 2]
 [3 4]
 [5 6]]


In [48]:
# 3. Staking (vstack, hstack)
# Es como concatenar pero mas visual

a = np.array([[1],[2],[3]])
b = np.array([[10],[20],[30]])
print(np.hstack((a,b)))
print("\n")
print(np.vstack((a,b)))

[[ 1 10]
 [ 2 20]
 [ 3 30]]


[[ 1]
 [ 2]
 [ 3]
 [10]
 [20]
 [30]]


In [53]:
# 4. Split
# Divide arrays en partes iguales.

x = np.arange(16).reshape(4,4)
print(f"Filas:\n{np.split(x, 2)}")
print(f"Columnas:\n{np.split(x, 2, axis=0)}")

# All y Any
print(np.all(x > 20))
print(np.any(x > 12))

Filas:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
Columnas:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
False
True


In [58]:
# 5. Mesclando todo

a = np.arange(1,10).reshape(3,3)
b = np.array([1,2,3])

c = a * b              # broadcasting
d = np.hstack((a,c))  # stacking
e = np.split(d, 3)    # split

print(c)
print(d)
print(e)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[ 1  2  3  1  4  9]
 [ 4  5  6  4 10 18]
 [ 7  8  9  7 16 27]]
[array([[1, 2, 3, 1, 4, 9]]), array([[ 4,  5,  6,  4, 10, 18]]), array([[ 7,  8,  9,  7, 16, 27]])]
