<a href="https://colab.research.google.com/github/CiberNefty/Numpy_Pandas_CienciaDatos_V01/blob/main/Platz/Numpy/04_identificacion_Y_conteo_de_respuestas_unicas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Unique**

In [6]:
import numpy as np

In [4]:
survey_responses = np.array(['bueno',"excelente",'malo',
                             "bueno","malo","excelente",
                             "bueno","bueno","malo","excelente"])

print(np.unique(survey_responses))

['bueno' 'excelente' 'malo']


In [12]:
# Cuantas veces aparece un elemento:
unique_elements, indiceElemento, counts = np.unique(survey_responses, return_counts=True, return_index=True)
print(f"Elementos unicos: {unique_elements}")
print(f"Indice de cada elemento: {indiceElemento}")
print(f"Cuantos elementos tiene cada uno: {counts}")

Elementos unicos: ['bueno' 'excelente' 'malo']
Indice de cada elemento: [0 1 2]
Cuantos elementos tiene cada uno: [4 3 3]


**Copia / Visatas**

In [16]:
# Vistas
array_x = np.arange(10)
view_y = array_x[1:3]

print(array_x)
print(view_y)

# Cambiar elementos desde una posicion
array_x[1:3] = [10,11]
print(array_x)
print(view_y)


[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [19]:
# Copia
array_x = np.arange(10)
copy_x = array_x[1:3].copy()
#copy_x = array_x[[1,2]]
print(array_x)
print(copy_x)
array_x[1:3] = [10,11]
print(array_x)
print(copy_x)


[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]
