<a href="https://colab.research.google.com/github/CiberNefty/Numpy_Pandas_CienciaDatos_V01/blob/main/Platz/Numpy/05_Manipulacion_de_Matrices_Arrays%2CTrasnponer_Invertir_Aplanar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Manipulacion De Matrices y Arrays en Numpy: Transponer, Invertir y Aplanar**

*Aprender a transponer y transformar matrices, invertir arrays y aplanar arrays multidimensionales son habilidades esenciales para manejar grandes volumenes de datos y realizar callculos complejos de manera eficiente.*

In [1]:
# Transposición de matrices
import numpy as np

In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
transposed_matrix = matrix.T
print("Matriz original:\n", matrix)
print("Matriz Transpuesta:\n", transposed_matrix)

Matriz original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz Transpuesta:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


**Cambair la forma (Reshape) de un array**

La funcion reshape permite cambiar la forma de un array sin cambiar sus datos. Es importante asegurarse de que el numero total de elementos permanezca constante.

Por ejemplo un array de 12 elementos puede ser remodelado en una matrix de 3x4, 4x3, 2x6, etc, pero no en una matriz de 5x3.

In [7]:
# Crear un array con lso numero del 1 al 12
array = np.arange(1,13)
# Cambia la forma del array a una matriz de 3 filas y 4 columnas
reshape_array = array.reshape(3,4)
print("Array original: ", array)
print("Array reshape a 3x4:\n", reshape_array)

Array original:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Array reshape a 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
# Invertir un array

# Crear un array con los numero del 1 al 5
array = np.array([1,2,3,4,5])

# Invertir array
reversed_array = array[::-1]
print("Array original: ", array)
print("Array invertido: ", reversed_array)

Array original:  [1 2 3 4 5]
Array invertido:  [5 4 3 2 1]


array[::-1] Invierte el array utiilizando slicing. array[star:stop:step] es la notacion general para slicing en Python, donde start es el indice incial, stop es indice final(excluido) y, step es el tamaño del paso. Al omitir start y stop y usar 1 como step, se obtiene una copia del array en orden inverso.

**Falttening de Arrays Multidimensionales**

El aplanamiento de arrays es el proceso de convertir un array multidimensional en un array unidemensional, es util en algoritmos que requieren una entrada lineal o para operaciones de agregacion. En numpy se puede aplanar un array usando flatten()

In [10]:
# Crear un array 2D
multi_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Aplana el array 2D a 1D
flattened_array = multi_array.flatten()

print("Array multidimensional:\n", multi_array)
print("Array aplanado:\n", flattened_array)

Array multidimensional:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array aplanado:
 [1 2 3 4 5 6 7 8 9]


multi_array.flatten() convierte un array 2D en un array 1D, escencialmente "aplanado" la estructura multidimensional. Esto es util para algoritmos que requieren una entrada unidimensional o para facilitar operaciones de agregacion.

La operacion flatten() siempre crea una copia asi que deemos asegurarnos de que esto es lo que deseamos para evitar problemas de memoria.