<a href="https://colab.research.google.com/github/CiberNefty/Numpy_Pandas_CienciaDatos_V01/blob/main/Platz/Numpy/06_Analisis_de_Ventas_transformaciones_y_Insights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Ejercicio: Analisis de Ventas Mensuales con Numpy***

El objetivo de este ejercicio es trabajar con arrays de numpy para analizar y manipular datos de ventas de tres productos a lo largo de un año. A través de diversas operaciones, explorar como usar numpu para obtener estadisticas, realozar manipulaciones avanzadas y aplicar tecnicas de indexacion para extraer informacion clave.

**Paso1 : Crear arrays con Datos de ventas**

* Usa la libreira de numpu para crear lo siguientes arrasy: Meses: un array con los nombres de los meses del año. Ventas_A,Ventas_B,Ventas_C: arrays que representen ventas mensuales de tres productos diferentes.

**Paso2: Estadisticas Basicas**
- Calcula la media y la suma de ventas para productos A,B y C usando las funciones de numoy.
* IMprime estos valores en el formato siguiente:
* Media de ventas Producto A: <valor>
* Suma de ventas Producto A: <valor>
* Repite para los productos B y C.

**Paso 4: Operaciones avanzadas con Numpy**

Reshape y Transposicion:
* Crea una matriz 2D con las ventas de los tres productos y transforma su forma(resahpe) a un array tridimensional con dimensiones (3,4,4)
* Trasnpone la matriz de ventas para que las filas se conviertan en columnas.
* Invierte arrays: Invierte las ventas de cada producto en orden de meses.
* Aplanar la matriz: Convierte la matriz a un array unidimensional.

**Paso 5: Analisis de Elementos unicos**

* Utiliza np.unique para encontrar los elementos unicos en los datos de ventas y cuenta cuantas veces aparece cada uno.

**Paso 6: Indexacion y Slicing**

* Ventas de primer trimestre: Extrae las ventas de los primeros meses del año.
* Indexacion booleana: Selecciona los meses donde el total de ventas de los tres productos supere los 800.
* Seleccion avanzada: usa una lista de indices para seleccionar las ventas de los meses pares (o selecciona los meses a tu eleccion) y muestras esas ventas en una nueva matriz.

In [1]:
import numpy as np

In [2]:
# Paso 1
months = np.array(['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio',
                   'Agosto','Septiembre','Octubre','Noviembre','Diciembre'])
ventas_pruducto_A = np.array([150,200,250,300,220,210,180,190,230,240,280,300])
ventas_pruducto_B = np.array([180,210,230,250,270,260,240,250,270,290,310,330])
ventas_pruducto_C = np.array([200,220,240,260,280,300,320,340,360,380,400,420])


In [11]:
# Paso 2: Resuelto

# Suma de ventas a,b,c totales
ventas_totales = np.sum([ventas_pruducto_A,ventas_pruducto_B,ventas_pruducto_C])
print(f"Ventas totales de los productos A,B,C: ${ventas_totales}")


# Media de las ventas del ´producto A:
media_prodcutoA = np.mean(ventas_pruducto_A)
print(f"\nMedia de las ventas del producto A: {media_prodcutoA}")
print(f"Suma de las ventas del producto A: {np.sum(ventas_pruducto_A)}")
# Media de las ventas del ´producto B:
media_prodcutoB = np.mean(ventas_pruducto_B)
print(f"\nMedia de las ventas del producto B: {media_prodcutoB}")
print(f"Suma de las ventas del producto B: {np.sum(ventas_pruducto_B)}")
# Media de las ventas del ´producto C:
media_prodcutoC = np.mean(ventas_pruducto_C)
print(f"\nMedia de las ventas del producto C: {media_prodcutoC}")
print(f"Suma de las ventas del producto C: {np.sum(ventas_pruducto_C)}")

Ventas totales de los productos A,B,C: $9560

Media de las ventas del producto A: 229.16666666666666
Suma de las ventas del producto A: 2750

Media de las ventas del producto B: 257.5
Suma de las ventas del producto B: 3090

Media de las ventas del producto C: 310.0
Suma de las ventas del producto C: 3720


In [63]:
# Paso 3: Resuelto
"""
Reshape y Transposicion:

Crea una matriz 2D con las ventas de los tres productos y transforma su forma(resahpe)
a un array tridimensional con dimensiones (3,4,4)
Trasnpone la matriz de ventas para que las filas se conviertan en columnas.
Invierte arrays: Invierte las ventas de cada producto en orden de meses.
Aplanar la matriz: Convierte la matriz a un array unidimensional.
"""
matrix_2d = np.array([ventas_pruducto_A,ventas_pruducto_B,ventas_pruducto_C])
matrix_reshape = matrix_2d.reshape(3,3,4)
matrix_transpose = matrix_2d.transpose()
matrix_inversa_meses = matrix_2d[:, ::-1]
matrix_aplanada = matrix_2d.flatten()
print(f"Matriz todas lassventas 2D:\n {matrix_2d}\n")
print(f"Forma Reshape 3x4x4:\n {matrix_reshape}\n")
print(f"Forma transponer de filas a columnas:\n {matrix_transpose}\n")
print(f"Forma matrix inversa por meses:\n {matrix_inversa_meses}\n")
print(f"Forma de matrix aplanada:\n {matrix_aplanada}")





Matriz todas lassventas 2D:
 [[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]

Forma Reshape 3x4x4:
 [[[150 200 250 300]
  [220 210 180 190]
  [230 240 280 300]]

 [[180 210 230 250]
  [270 260 240 250]
  [270 290 310 330]]

 [[200 220 240 260]
  [280 300 320 340]
  [360 380 400 420]]]

Forma transponer de filas a columnas:
 [[150 180 200]
 [200 210 220]
 [250 230 240]
 [300 250 260]
 [220 270 280]
 [210 260 300]
 [180 240 320]
 [190 250 340]
 [230 270 360]
 [240 290 380]
 [280 310 400]
 [300 330 420]]

Forma matrix inversa:
 [[300 280 240 230 190 180 210 220 300 250 200 150]
 [330 310 290 270 250 240 260 270 250 230 210 180]
 [420 400 380 360 340 320 300 280 260 240 220 200]]

Forma de matrix aplanada:
 [150 200 250 300 220 210 180 190 230 240 280 300 180 210 230 250 270 260
 240 250 270 290 310 330 200 220 240 260 280 300 320 340 360 380 400 420]
