<a href="https://colab.research.google.com/github/CiberNefty/Numpy_Pandas_CienciaDatos_V01/blob/main/Platz/Numpy/07_Operaciones_de_AlbebraLineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Operaciondes de Álgebra Lineal con Numpy**

Ver documentacion:
https://numpy.org/doc/stable/reference/routines.linalg.html



In [2]:
import numpy as np

In [4]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

¿Como realizar la suma y resta de matrices?

La suma y resta de amtrices con Numpy es directa. Basta con utilizar los operadores + para edicion y - para sustraccion, respectivamente.

In [5]:
# Suma de matrices
sum = a+b
print(sum)
# Resta de matrices
resta = a-b
print(resta)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


¿Como realizar una multiplicacion matricual?

La multiplicacion entre matrices, tambien conocida como producto matricial, se realiza con la funcion dot de Numpy:

In [6]:
# Producto Matricial
prodcuto = np.dot(a,b)
print(prodcuto)

[[19 22]
 [43 50]]


¿Como calcular el determinante y la inversa de una matriz?

Numpy tambien ofrece funciones para calcular el determinante e inversa de una matriz, elementos fundamentales en algebra lineal.

In [10]:
# DETERMINANTE
determinante = np.linalg.det(a)
print(determinante)

-2.0000000000000004


EL determinante es un numero unico que puede proporcionar informacion sobre las propiedades de la matriz, como si es invertible o no.

In [11]:
# INVERSA
inversa = np.linalg.inv(a)
print(inversa)

[[-2.   1. ]
 [ 1.5 -0.5]]


La inversa es una matriz tal que, cuando se multiplica la matriz original, produce la matriz indentidad.

¿Como resolver un sistema de ecuaciones lineales con matrices?

Numpy facilita la resolucion de sistemas de ecuaciones lineales de la forma(A \ times X=B), donde necesitas encontrar (X).

In [12]:
# Resolver sistema de ecuaciones lineales
b = np.array([9,11])
X = np.linalg.solve(a,b)
print(X)

[-7.  8.]


Este calculo devuelve el vector X que satisface el sistema de ecuaciones.

Estas operaciones son la base para el manero de datos en grandes volumenes , y pueden ser extendidas a situaciones mas complejas dependiendo del tipo de problema que enfrente.