<a href="https://colab.research.google.com/github/CiberNefty/Numpy_Pandas_CienciaDatos_V01/blob/main/Platz/Numpy/Manipulacion_de_arrays_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Manipulacion de Arrays**

In [1]:
import numpy as np

In [3]:
array = np.array([[1,2,3],[4,5,6]])
print(array.ndim) # Dimension del array
print(array.shape) # un vector de 2 x 3
print(array.dtype) # Tipo de dato int64

2
(2, 3)
int64


In [6]:
z = np.array(3, dtype= np.uint8)
print(z)

[[1 2 3]
 [4 5 6]]


In [7]:
double_array = np.array([1,2,3], dtype='d')
print(double_array)

[1. 2. 3.]


In [8]:
z = z.astype(np.float64)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]


In [11]:
# SUMA
array = np.array([[1,2,3],[4,5,6]])
add = np.sum(array)
print(add)

21


In [12]:
# MEDIA
mean = np.mean(array)
print(mean)

3.5


In [13]:
# DESVIACION ESTANDAR
std = np.std(array)
print(std)

1.707825127659933
