<a href="https://colab.research.google.com/github/CiberNefty/Numpy_Pandas_CienciaDatos_V01/blob/main/Numpy/01_Arrays_basicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy pandas matplotlib

In [ ]:
import numpy as np
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [ ]:
vector = np.array([30,22,34,12,19,20,42])
print(vector)

[30 22 34 12 19 20 42]


In [ ]:
# Matricez para varios vectores (2 dimensiones)
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [ ]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
eye_matrix = np.eye(6)
print(eye_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
from IPython.utils.sysinfo import pprint
diag = np.diag([1,2,3,4])
print(diag)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
random = np.random.random((2,3))
print(random)

[[0.86083342 0.79775722 0.56028979]
 [0.53221429 0.88652396 0.32335997]]
